/**
 * End-to-end logic test for the UrbanSafe emergency flow using the demo
 * store (no Firebase configured). Simulates two nearby demo users:
 *
 *   demo-a sends an SOS  ->  demo-b receives a sanitized real-time alert
 *   demo-a resolves      ->  demo-b's alert disappears
 *
 * Run with: node scripts/emergency-e2e-test.cjs
 * (generated by esbuild from scripts/emergency-e2e-test.ts)
 */

// Must run first: polyfills window/localStorage/BroadcastChannel for Node.
import "./node-env-setup";

import {
  createEmergency,
  getEmergencyHistory,
  getMyLocation,
  getSimulatedLocation,
  resolveEmergency,
  subscribeMyEvents,
  subscribeNearbyEmergencies,
} from "../src/services/emergency";
import { encodeGeohash, decodeGeohash, geohashBoundsForRadius, geohashNeighbor } from "../src/lib/geohash";
import { formatDistance, haversineMeters, approximateLocation, timeAgo } from "../src/lib/geo";

let failures = 0;
function check(label: string, condition: boolean, detail?: unknown) {
  if (condition) {
    console.log(`  PASS  ${label}`);
  } else {
    failures += 1;
    console.error(`  FAIL  ${label}`, detail ?? "");
  }
}

async function main() {
  console.log("\n== geo utilities ==");
  check("geohash encode known vector (57.64911, 10.40744) -> u4pruyd", encodeGeohash(57.64911, 10.40744, 7) === "u4pruyd", encodeGeohash(57.64911, 10.40744, 7));
  const decoded = decodeGeohash("u4pruyd");
  check("geohash decode round-trips within ~1e-3", Math.abs(decoded.latitude - 57.64911) < 0.001 && Math.abs(decoded.longitude - 10.40744) < 0.001, decoded);
  check("haversine (0,0)->(0,1) ~111.2 km", Math.abs(haversineMeters(0, 0, 0, 1) - 111195) < 200, haversineMeters(0, 0, 0, 1));
  check("formatDistance 700 -> '700 m'", formatDistance(700) === "700 m");
  check("formatDistance 1200 -> '1.2 km'", formatDistance(1200) === "1.2 km");
  check("approximateLocation rounds to 4dp", JSON.stringify(approximateLocation(26.9124567, 75.7873456)) === '{"latitude":26.9125,"longitude":75.7873}');
  check("timeAgo now -> 'Just now'", timeAgo(Date.now()) === "Just now");
  const bounds = geohashBoundsForRadius(26.9124, 75.7873, 2000);
  check("geohash bounds produce a sorted cell range", bounds.min <= bounds.max && bounds.cells.length >= 5, bounds.cells);

  const center = encodeGeohash(26.9124, 75.7873, 7);
  const nHash = geohashNeighbor(center, "n");
  const sHash = geohashNeighbor(center, "s");
  const eHash = geohashNeighbor(center, "e");
  const wHash = geohashNeighbor(center, "w");
  const cDec = decodeGeohash(center);
  check("north neighbor is north", decodeGeohash(nHash).latitude > cDec.latitude, nHash);
  check("south neighbor is south", decodeGeohash(sHash).latitude < cDec.latitude, sHash);
  check("east neighbor is east", decodeGeohash(eHash).longitude > cDec.longitude, eHash);
  check("west neighbor is west", decodeGeohash(wHash).longitude < cDec.longitude, wHash);
  check("neighbor round-trips (n then s)", geohashNeighbor(nHash, "s") === center, `${geohashNeighbor(nHash, "s")} vs ${center}`);
  check("neighbor round-trips (e then w)", geohashNeighbor(eHash, "w") === center, `${geohashNeighbor(eHash, "w")} vs ${center}`);
  check("neighbor is a valid same-length hash", nHash.length === center.length && eHash.length === center.length, [nHash, eHash]);

  console.log("\n== simulated locations ==");
  const locA = await getMyLocation("demo-a@urbansafe.test");
  const locB = await getMyLocation("demo-b@urbansafe.test");
  check("demo location permission is 'demo'", locA.permission === "demo", locA);
  check("demo locations are deterministic", JSON.stringify(await getMyLocation("demo-a@urbansafe.test")) === JSON.stringify(locA));
  const distanceAB = haversineMeters(locA.latitude, locA.longitude, locB.latitude, locB.longitude);
  check("two demo users are within the 2 km radius", distanceAB < 2000, `${Math.round(distanceAB)} m`);
  console.log(`  INFO  distance between demo users: ${formatDistance(distanceAB)}`);

  console.log("\n== two-user community SOS flow ==");
  const uidA = "demo-a@urbansafe.test";
  const uidB = "demo-b@urbansafe.test";

  const receivedByB: Array<{ id: string; type: string; message: string | null; distance: number | null }> = [];
  const myActiveA: string[] = [];

  const unsubB = subscribeNearbyEmergencies({
    uid: uidB,
    location: locB,
    onEvents: (events) => {
      receivedByB.length = 0;
      receivedByB.push(...events.map((e) => ({ id: e.id, type: e.type, message: e.message, distance: e.distanceMeters })));
    },
  });
  const unsubA = subscribeMyEvents(uidA, (events) => {
    myActiveA.length = 0;
    myActiveA.push(...events.map((e) => `${e.id}:${e.status}`));
  });

  // A creates an emergency with type + message.
  const result = await createEmergency(uidA, { type: "accident", message: "Accident on the road" });
  const event = result.event;
  check("event stored with status active", event.status === "active", event);
  check("event has approximate location", Math.abs(event.latitude - locA.latitude) < 0.0001 && Math.abs(event.longitude - locA.longitude) < 0.0001, event);
  check("event has a geohash", event.geohash.length >= 5, event.geohash);
  check("event has createdAt/expiresAt", event.createdAt > 0 && event.expiresAt > event.createdAt);

  // Wait a tick for listeners.
  await new Promise((resolve) => setTimeout(resolve, 50));

  check("reporter sees their active SOS", myActiveA.some((entry) => entry === `${event.id}:active`), myActiveA);
  check("nearby user B received the alert", receivedByB.some((e) => e.id === event.id), receivedByB);
  const received = receivedByB.find((e) => e.id === event.id);
  check("alert carries the emergency type", received?.type === "accident", received);
  check("alert carries the shared short text", received?.message === "Accident on the road", received);
  check("alert does NOT reveal the reporter uid", Boolean(received && !("createdBy" in (received as object))), received);
  check("alert distance is within the radius", Boolean(received && received.distance !== null && received.distance <= 2000), received);
  console.log(`  INFO  demo-b sees alert ${formatDistance(received?.distance ?? 0)} away`);

  // Self-notification guard.
  const receivedByA: Array<{ id: string }> = [];
  const unsubASelf = subscribeNearbyEmergencies({
    uid: uidA,
    location: locA,
    onEvents: (events) => {
      receivedByA.length = 0;
      receivedByA.push(...events.map((e) => ({ id: e.id })));
    },
  });
  await new Promise((resolve) => setTimeout(resolve, 50));
  check("reporter does NOT receive their own alert", !receivedByA.some((e) => e.id === event.id), receivedByA);

  // Text emergency without message (quick SOS).
  const quickResult = await createEmergency(uidA, { type: "general" });
  check("quick SOS (no message) stores message null", quickResult.event.message === null);

  // History.
  const history = await getEmergencyHistory(uidA);
  check("history contains both events (newest first)", history.length >= 2 && history[0].id === quickResult.event.id, history.map((e) => e.id));

  // Resolve flow.
  await resolveEmergency(uidA, event.id);
  await new Promise((resolve) => setTimeout(resolve, 50));
  check("reporter's active SOS is gone after resolve", !myActiveA.some((entry) => entry === `${event.id}:active`), myActiveA);
  check("nearby user B no longer sees the resolved alert", !receivedByB.some((e) => e.id === event.id), receivedByB);
  check("history shows resolved status", (await getEmergencyHistory(uidA)).some((e) => e.id === event.id && e.status === "resolved"));

  // Unauthorized resolve guard (demo store).
  await resolveEmergency(uidB, quickResult.event.id);
  await new Promise((resolve) => setTimeout(resolve, 50));
  check("another user cannot resolve someone else's SOS", (await getEmergencyHistory(uidA)).some((e) => e.id === quickResult.event.id && e.status === "active"));

  unsubB();
  unsubA();
  unsubASelf();

  console.log("\n==============================================");
  if (failures === 0) {
    console.log("ALL CHECKS PASSED — emergency flow works end-to-end");
  } else {
    console.error(`${failures} CHECK(S) FAILED`);
    process.exitCode = 1;
  }
}

void main();
